version: '3.2'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=valkyrie
      - POSTGRES_USER=odin
      - POSTGRES_PASSWORD=Welc0me2Valhalla
    ports:
      - 5432:5432

  valkyrie:
    build: .
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/valkyrie
      - DATABASE_USER=odin
      - DATABASE_PASSWORD=Welc0me2Valhalla
    volumes:
      - ./front-vue/dist/:/pages/
    ports:
      - 9000:9000
    depends_on:
      - postgres
